name       : python-tifffile
version    : 2022.5.4
release    : 1
source     :
    - https://files.pythonhosted.org/packages/source/t/tifffile/tifffile-2022.5.4.tar.gz : b03147a15862b7c1d90d47435197f149bef7a52c25ad67cf1f9b465faa71b8d2
homepage   : https://www.lfd.uci.edu/~gohlke/
license    : BSD-3-Clause
component  : programming.python
summary    : Read and write TIFF files
description: |
    Tifffile is a Python library to store numpy arrays in TIFF (Tagged Image File Format) files, and read image and metadata from TIFF-like files used in bioimaging.
rundeps    :
    - numpy
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    # requires packaging python-fsspec and python-xarray
#    %python3_test pytest3 -v
